name: Build it!
on:
  push:

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update repository
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: kludex/update-file@main
        with:
          script_file: script.py
          update_file: README.md
