name: Build it!

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  schedule:
    - cron: "0 */2 * * *"

jobs:
  resources:
    name: Update resources
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install requests

      - name: Run updater
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python script.py  # make sure this writes README.md and data.tsv

      - name: Commit README.md and data.tsv
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update README.md and data.tsv"
          file_pattern: "README.md data.tsv"

