name: Build it!
on: [push, pull_request]
jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update repository
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: Kludex/update-file@0.6.1
        with:
          script_file: script.py
          update_file: README.md
